project:
  execute-dir: project
format:
  docx:
    toc: false
    echo: false
    # fig-format: svg
    toc-depth: 4
    cap-location: top
    fig-cap-location: top
    tbl-cap-location: top
    number-sections: true
    number-depth: 3
    link-citations: true
    date: last-modified
    date-format: "[Last modified:] YYYY-MM-DD: H:mm:ss (A)"
    bibliography: references.bib
    embed-resources: true
    appendix-style: plain
    mainfont: serif
  html:
    # author:
    #   - name: Ezra Morrison
    #     email: demorrison@ucdavis.edu
    #   - Matt Ponzini
    #   - Kyoungmi Kim
    #   - (more to be added)
    toc: true
    # fig-format: svg
    toc-float: true
    toc-depth: 4
    embed-resources: true
    appendix-style: plain
    mainfont: serif
    theme:
       light:
         - cosmo
         - custom.scss
       dark:
         - darkly
         - custom.scss
    css: custom.scss
    number-sections: true
    number-depth: 3
    html-math-method: mathjax
    cap-location: top
    fig-cap-location: top
    tbl-cap-location: top
    code-fold: true
    echo: false
    date: last-modified
    date-format: "[Last modified:] YYYY-MM-DD: H:mm:ss (A)"
    bibliography: references.bib
knitr:
  opts_chunk:
    collapse: true
    comment: "#>"
    R.options:
      dev: svg
execute:
  warning: false
  message: false
  cache: false
  freeze: auto  # re-render only when source changes
filters:
  - docx-landscape.lua
