authors:
  - name: Douglas Ezra Morrison
    affiliations:
      - ref: ucdphs
    corresponding: true
    email: demorrison@ucdavis.edu
    address: One Shields Ave, Davis, CA 95616

  - name: Matthew Ponzini
    affiliations:
      - ref: ucdphs
  - name: Ellery R. Santos
    affiliations:
      - ref: ucdmind
  - name: Hazel Maridith Barlahan Biag
    affiliations:
      - ref: ucdmind
  - name: Glenda Espinal
    affiliations:
      - ref: ucdmind
  - name: Flora Tassone
    affiliations:
      - ref: ucdmind
      - ref: ucdbiochem
  - name: David Hessl
    affiliations:
      - ref: ucdmind
      - ref: ucdpsych
  - name: Susan Rivera
    affiliations:
      - ref: umdpsychology
  - name: Andrea Schneider
    affiliation:
      - ref: ucdmind
  - name: James A. Bourgeois
    affiliation:
      - ref: ucdpsych
  - name: Randi Hagerman
    affiliation:
      - ref: ucdmind
      - ref: ucdpeds
  - name: Kyoungmi Kim
    affiliation:
      - ref: ucdphs

affiliations:
  - id: umdpsychology
    name: Department of Psychology, College of Behavioral and Social Sciences, University of Maryland, College Park, MD, United States
    department: Department of Psychology
    city: College Park
    state: MD
    country: United States
  - id: ucdmind
    department: MIND Institute
    name: MIND Institute, University of California, Davis, Sacramento, CA, United States
    city: Sacramento
    state: CA
    country: United States
  - id: ucdphs
    name: Department of Public Health Sciences, School of Medicine, University of California, Davis, CA, United States
    department: Department of Public Health Sciences
    city: Davis
    state: CA
    country: United States
  - id: ucdmind
    department: MIND Institute
    name: MIND Institute, University of California, Davis, Sacramento, CA, United States
    city: Sacramento
    state: CA
    country: United States
  - id: ucdbiochem
    department: Department of Biochemistry and Molecular Medicine
    name: Department of Biochemistry and Molecular Medicine, School of Medicine, University of California, Davis, Sacramento CA, United States
    state: CA
    country: United States
  - id: ucdpsych
    department: Department of Psychiatry and Behavioral Sciences
    name: Department of Psychiatry and Behavioral Sciences, University of California, Davis, Medical Center, Sacramento CA, United States
    city: Sacramento
    state: CA
    country: United States
  - id: ucdpeds
    department: Department of Pediatrics
    name: Department of Pediatrics, University of California, Davis Medical Center, Sacramento, CA, United States
    city: Sacramento
    state: CA
    country: United States
project:
  execute-dir: project
format:
  docx:
    reference-doc: vignettes/Brain_template_2022.docx
    csl: vignettes/brain.csl
    toc: false
    echo: false
    # fig-format: svg
    fig-dpi: 300
    # dpi: 300
    toc-depth: 4
    cap-location: top
    fig-cap-location: top
    appendix-title: "Sup."
    tbl-cap-location: top
    number-sections: true
    number-depth: 3
    link-citations: true
    date: last-modified
    date-format: "[Last modified:] YYYY-MM-DD: H:mm:ss (A)"
    embed-resources: true
    appendix-style: plain
    mainfont: serif
  pdf:
    documentclass: scrartcl
  html:
    toc: true
    # fig-format: svg
    toc-float: true
    toc-depth: 4
    embed-resources: true
    appendix-style: plain
    mainfont: serif
    theme:
       light:
         - cosmo
         - vignettes/custom.scss
       dark:
         - darkly
         - vignettes/custom.scss
    css: vignettes/custom.scss
    number-sections: true
    number-depth: 3
    html-math-method: mathjax
    cap-location: top
    fig-cap-location: top
    tbl-cap-location: top
    code-fold: true
    echo: false
    date: last-modified
    date-format: "[Last modified:] YYYY-MM-DD: H:mm:ss (A)"
bibliography: vignettes/references.bib
knitr:
  opts_chunk:
    collapse: true
    comment: "#>"
    R.options:
      dev: svg
execute:
  warning: false
  message: false
  cache: false
  freeze: false  # re-render only when source changes
filters:
  - vignettes/docx-landscape.lua
  - authors-block
