---
name: Spellcheck

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  check:
    runs-on: ubuntu-latest
    name: Spellcheck
    container:
      image: rocker/tidyverse:4.1.2
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Run Spelling Check test
        uses: insightsengineering/r-spellcheck-action@HEAD
