# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:
  push:
    branches: [main, master]
  pull_request:

name: R-CMD-check.yaml

permissions: read-all

jobs:
  R-CMD-check:
    runs-on: ${{ matrix.config.os }}

    name: ${{ matrix.config.os }} (${{ matrix.config.r }})

    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: windows-latest,   r: 'release'}

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes

    steps:
      - uses: actions/checkout@HEAD

      - uses: r-lib/actions/setup-pandoc@HEAD

      - uses: actions/setup-python@HEAD
        with:
          python-version: '3.9'

      - uses: r-lib/actions/setup-r@HEAD
        with:
          r-version: ${{ matrix.config.r }}
          http-user-agent: ${{ matrix.config.http-user-agent }}
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@HEAD
        with:
          extra-packages: any::rcmdcheck, local::.
          needs: check

      - name: setup r-reticulate venv
        shell: Rscript {0}
        run: |

          library(reticulate)
          reticulate::py_require(
            packages = c(
              "git+https://github.com/ucl-pond/kde_ebm",
              "git+https://github.com/d-morrison/pySuStaIn"
            ),
            python_version = "3.9"
          )
          reticulate::py_config()

      - uses: r-lib/actions/check-r-package@HEAD
        with:
          upload-snapshots: true
          error-on: '"warning"'
          build_args: 'c("--no-manual","--compact-vignettes=gs+qpdf")'
